<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ApexInsurance.Dto</RootNamespace>
    <AssemblyName>ApexInsurance.Dto</AssemblyName>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApexInsurance.Domain\ApexInsurance.Domain.csproj" />
  </ItemGroup>

</Project>
